using JobOrbit.Application.Authorization;using JobOrbit.Application.DTOs.AdminApplications;using JobOrbit.Application.Interfaces;using JobOrbit.Domain.Enums;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JobOrbit.API.Controllers;
[ApiController,Route("api/admin/applications"),Authorize(Roles=nameof(UserRole.Administrator))]public sealed class AdminApplicationsController(IAdminApplicationService service,IAuditService audit):ControllerBase
{
 bool UserId(out int id)=>int.TryParse(User.FindFirst("UserId")?.Value,out id);
 [HttpGet,Authorize(Policy=PermissionConstants.AdminApplicationsView)]public async Task<IActionResult>List([FromQuery]AdminApplicationQuery q,CancellationToken t){var x=await service.ListAsync(q,t);return x.Valid?Ok(x.Result):x.Error?.EndsWith("not found")==true?NotFound(new ProblemDetails{Status=404,Title=x.Error}):BadRequest(new ProblemDetails{Status=400,Title=x.Error});}
 [HttpGet("{applicationId:int}"),Authorize(Policy=PermissionConstants.AdminApplicationsView)]public async Task<IActionResult>Details(int applicationId,CancellationToken t)=>await service.DetailsAsync(applicationId,t)is{}x?Ok(x):NotFound(new ProblemDetails{Status=404,Title="Application not found"});
 [HttpGet("{applicationId:int}/resume"),Authorize(Policy=PermissionConstants.AdminApplicationsView)]public async Task<IActionResult>Resume(int applicationId,CancellationToken t){var x=await service.DownloadResumeAsync(applicationId,t);if(x is null)return NotFound(new ProblemDetails{Status=404,Title="Resume not found"});if(!UserId(out var id))return Unauthorized();await audit.WriteAsync(new JobOrbit.Application.Auditing.AuditEvent(id,"ResumeAccessed",nameof(JobOrbit.Domain.Entities.JobApplication),applicationId,Description:"Administrator downloaded an application resume."),t);return File(x.Content,x.ContentType,x.FileName);}
 [HttpGet("{applicationId:int}/history"),Authorize(Policy=PermissionConstants.AdminApplicationsView)]public async Task<IActionResult>History(int applicationId,CancellationToken t)=>await service.HistoryAsync(applicationId,t)is{}x?Ok(x):NotFound(new ProblemDetails{Status=404,Title="Application not found"});
 [HttpPatch("{applicationId:int}/status"),Authorize(Policy=PermissionConstants.AdminApplicationsManage)]public async Task<IActionResult>Status(int applicationId,UpdateAdminApplicationStatusRequest r,CancellationToken t){if(!UserId(out var id))return Unauthorized();var x=await service.UpdateStatusAsync(id,applicationId,r,t);return x.Outcome switch{AdminApplicationMutationOutcome.Success=>Ok(x.Application),AdminApplicationMutationOutcome.NotFound=>NotFound(new ProblemDetails{Status=404,Title="Application not found"}),AdminApplicationMutationOutcome.InvalidStatus=>BadRequest(new ProblemDetails{Status=400,Title="Invalid application status"}),AdminApplicationMutationOutcome.FinalDecisionConflict=>Conflict(new ProblemDetails{Status=409,Title="Status conflicts with a final hiring decision",Detail="Correct the final hiring decision through its owning workflow before changing this application status."}),_=>Conflict(new ProblemDetails{Status=409,Title="The requested administrative status correction is not allowed"})};}
}
