using JobOrbit.Application.DTOs.Jobs;using JobOrbit.Application.DTOs.RecruiterInterviews;using JobOrbit.Application.Interfaces;using JobOrbit.Domain.Enums;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JobOrbit.API.Controllers;
[ApiController,Route("api/recruiter/interviews"),Authorize(Roles=nameof(UserRole.Recruiter))]
public sealed class RecruiterInterviewsController(IRecruiterInterviewService service):ControllerBase
{
 private bool UserId(out int id)=>int.TryParse(User.FindFirst("UserId")?.Value,out id);
 [HttpPost]public async Task<ActionResult> Create(CreateInterviewRequest request,CancellationToken token){if(!UserId(out var id))return Unauthorized();var result=await service.CreateAsync(id,request,token);return result.Outcome switch{RecruiterInterviewOutcome.Success=>CreatedAtAction(nameof(Details),new{interviewId=result.InterviewId},new{interviewId=result.InterviewId}),RecruiterInterviewOutcome.NotFound=>NotFound(),RecruiterInterviewOutcome.ApplicationNotShortlisted=>Conflict(Problem("Application must be shortlisted before scheduling")),RecruiterInterviewOutcome.DuplicateActiveInterview=>Conflict(Problem("An active interview already exists for this application")),_=>BadRequest()};}
 [HttpGet]public async Task<ActionResult<PagedResultDto<RecruiterInterviewListItemDto>>>List([FromQuery]RecruiterInterviewQuery query,CancellationToken token){if(!UserId(out var id))return Unauthorized();if(!string.IsNullOrWhiteSpace(query.Status)&&!Enum.TryParse<InterviewStatus>(query.Status,true,out _))return BadRequest(Problem("Invalid interview status",400));if(query.From>query.To)return BadRequest(Problem("The from date must be before the to date",400));return Ok(await service.ListAsync(id,query,token));}
 [HttpGet("shortlisted-applications")]public async Task<ActionResult<IReadOnlyList<ShortlistedApplicationDto>>>Shortlisted(CancellationToken token)=>UserId(out var id)?Ok(await service.ShortlistedAsync(id,token)):Unauthorized();
 [HttpGet("{interviewId:int}")]public async Task<ActionResult<RecruiterInterviewDetailsDto>>Details(int interviewId,CancellationToken token)=>UserId(out var id)?(await service.DetailsAsync(id,interviewId,token)is{}x?Ok(x):NotFound()):Unauthorized();
 [HttpPut("{interviewId:int}")]public async Task<IActionResult>Update(int interviewId,UpdateInterviewRequest request,CancellationToken token)=>UserId(out var id)?Outcome(await service.UpdateAsync(id,interviewId,request,token)):Unauthorized();
 [HttpPatch("{interviewId:int}/cancel")]public async Task<IActionResult>Cancel(int interviewId,CancellationToken token)=>UserId(out var id)?Outcome(await service.CancelAsync(id,interviewId,token)):Unauthorized();
 [HttpPatch("{interviewId:int}/complete")]public async Task<IActionResult>Complete(int interviewId,CancellationToken token)=>UserId(out var id)?Outcome(await service.CompleteAsync(id,interviewId,token)):Unauthorized();
 private IActionResult Outcome(RecruiterInterviewOutcome x)=>x switch{RecruiterInterviewOutcome.Success=>NoContent(),RecruiterInterviewOutcome.NotFound=>NotFound(),RecruiterInterviewOutcome.InvalidTransition=>Conflict(Problem("The requested interview transition is not allowed")),RecruiterInterviewOutcome.InterviewNotDue=>Conflict(Problem("A future interview cannot be completed")),_=>BadRequest()};private static ProblemDetails Problem(string title,int status=409)=>new(){Status=status,Title=title};
}
