using System.ComponentModel.DataAnnotations;using JobOrbit.Application.DTOs.Jobs;
namespace JobOrbit.Application.DTOs.AdminJobs;
public sealed class AdminJobQuery{public string?Search{get;set;}public string?Status{get;set;}public int?OrganizationId{get;set;}public int?DepartmentId{get;set;}public int?RecruiterId{get;set;}public string?EmploymentType{get;set;}public string?WorkplaceType{get;set;}public bool?IsFeatured{get;set;}public DateTime?From{get;set;}public DateTime?To{get;set;}[Range(1,int.MaxValue)]public int Page{get;set;}=1;[Range(1,100)]public int PageSize{get;set;}=10;public string Sort{get;set;}="newest";}
public sealed record AdminJobListItemDto(int JobId,string Title,int OrganizationId,string OrganizationName,int DepartmentId,string DepartmentName,int RecruiterId,string RecruiterName,string Status,string EmploymentType,string?WorkplaceType,string Location,int ApplicationCount,bool IsFeatured,DateTime?PublishedAt,DateTime?ClosingDate,DateTime CreatedAt);
public sealed record AdminJobOrganizationSummaryDto(int OrganizationId,string Name,string Code,bool IsActive);public sealed record AdminJobDepartmentSummaryDto(int DepartmentId,string Name,string Code,bool IsActive);public sealed record AdminJobRecruiterSummaryDto(int RecruiterId,string FullName,string Email,bool IsActive);
public sealed record AdminJobDetailsDto(int JobId,string Title,string Description,string?Requirements,string?Responsibilities,IReadOnlyList<string>Skills,AdminJobOrganizationSummaryDto Organization,AdminJobDepartmentSummaryDto Department,AdminJobRecruiterSummaryDto Recruiter,string Status,string EmploymentType,string?WorkplaceType,string Location,decimal?SalaryMin,decimal?SalaryMax,string Currency,string?ExperienceLevel,int VacancyCount,int ApplicationCount,int ShortlistedCount,int InterviewCount,int HiredCount,bool IsFeatured,DateTime?PublishedAt,DateTime?ClosingDate,DateTime CreatedAt,DateTime UpdatedAt);
public sealed class UpdateAdminJobRequest:IValidatableObject{[Required,MaxLength(200)]public string Title{get;set;}="";[Required,MaxLength(8000)]public string Description{get;set;}="";[MaxLength(8000)]public string?Requirements{get;set;}[MaxLength(8000)]public string?Responsibilities{get;set;}public List<string>Skills{get;set;}=[];[Required,MaxLength(100)]public string EmploymentType{get;set;}="";[MaxLength(50)]public string?WorkplaceType{get;set;}[Required,MaxLength(200)]public string Location{get;set;}="";[Range(0,double.MaxValue)]public decimal?SalaryMin{get;set;}[Range(0,double.MaxValue)]public decimal?SalaryMax{get;set;}[Required,MaxLength(10)]public string Currency{get;set;}="LKR";[MaxLength(100)]public string?ExperienceLevel{get;set;}[Range(1,10000)]public int VacancyCount{get;set;}=1;public DateTime?ClosingDate{get;set;}public IEnumerable<ValidationResult>Validate(ValidationContext c){if(SalaryMin>SalaryMax)yield return new("Minimum salary must not exceed maximum salary.");if(ClosingDate.HasValue&&ClosingDate<=DateTime.UtcNow)yield return new("Closing date must be in the future.");if(Skills.Any(x=>string.IsNullOrWhiteSpace(x)||x.Trim().Length>100))yield return new("Skills must be between 1 and 100 characters.");}}
public sealed class UpdateAdminJobStatusRequest{[Required]public string Status{get;set;}="";[MaxLength(500)]public string?Reason{get;set;}}public sealed class UpdateAdminJobFeaturedRequest{public bool IsFeatured{get;set;}}
public enum AdminJobOutcome{Success,NotFound,InvalidStatus,InvalidTransition,InactiveOwnership,Expired,InvalidSkills,FeatureRequiresPublished}
public sealed record AdminJobResult(AdminJobOutcome Outcome,AdminJobDetailsDto?Job=null);public sealed record AdminJobListResult(bool Valid,PagedResultDto<AdminJobListItemDto>?Result=null,string?Error=null);
