using System.Globalization;
using System.Text.RegularExpressions;
using JobOrbit.Application.Auditing;
using JobOrbit.Application.DTOs.AdminSystemSettings;
using JobOrbit.Application.Interfaces;
using JobOrbit.Domain.Enums;

namespace JobOrbit.Application.Services;

public sealed class AdminSystemSettingsService(ISystemSettingsProvider provider,IAuditService audit):IAdminSystemSettingsService
{
 static readonly HashSet<string> DateFormats=["yyyy-MM-dd","dd/MM/yyyy","MM/dd/yyyy","dd MMM yyyy"];
 static readonly HashSet<string> ResumeExtensions=[".pdf",".doc",".docx"];
 static readonly HashSet<string> ImageExtensions=[".jpg",".jpeg",".png",".webp"];
 public Task<SystemSettingsDto> GetAsync(CancellationToken t=default)=>provider.GetAsync(t);
 public async Task<SystemSettingsMutationResult> UpdateGeneralAsync(int a,UpdateGeneralSettingsRequest r,CancellationToken t=default){var tz=TimeZoneInfo.GetSystemTimeZones().Any(x=>x.Id.Equals(r.DefaultTimeZone.Trim(),StringComparison.OrdinalIgnoreCase))||r.DefaultTimeZone.Trim()=="Asia/Colombo";if(!tz)return Bad("Unsupported timezone.");var c=r.DefaultCurrency.Trim().ToUpperInvariant();if(!Regex.IsMatch(c,"^[A-Z]{3}$"))return Bad("Currency must be a three-letter code.");if(!DateFormats.Contains(r.DateFormat))return Bad("Unsupported date format.");return await Save(a,"general",new GeneralSettingsDto(r.PlatformName.Trim(),r.SupportEmail.Trim().ToLowerInvariant(),r.DefaultTimeZone.Trim(),c,r.DateFormat),"GeneralSettingsUpdated",AuditSeverity.Information,t);}
 public async Task<SystemSettingsMutationResult> UpdateRecruitmentAsync(int a,UpdateRecruitmentSettingsRequest r,CancellationToken t=default){if(r.MinimumProfileCompletionPercent is <0 or >100)return Bad("Profile completion must be between 0 and 100.");if(r.DefaultJobClosingDays is <1 or >365)return Bad("Default closing days must be between 1 and 365.");if(r.AllowMultipleApplicationsPerJob)return new(false,null,"The current data model guarantees one application per candidate and job; enabling duplicates would be unsafe.",true);return await Save(a,"recruitment",new RecruitmentSettingsDto(r.AllowCandidateSelfRegistration,false,r.RequireProfileCompletionBeforeApply,r.MinimumProfileCompletionPercent,r.DefaultJobClosingDays,r.RequireEvaluationBeforeHiringDecision,r.RequireInterviewBeforeHiringDecision),"RecruitmentSettingsUpdated",AuditSeverity.Information,t);}
 public async Task<SystemSettingsMutationResult> UpdateUploadsAsync(int a,UpdateUploadSettingsRequest r,CancellationToken t=default){var resumes=Normalize(r.AllowedResumeExtensions);var images=Normalize(r.AllowedProfileImageExtensions);if(r.MaximumResumeSizeMb is <1 or >20||r.MaximumProfileImageSizeMb is <1 or >10)return Bad("Upload sizes are outside the safe range.");if(resumes.Length==0||resumes.Any(x=>!ResumeExtensions.Contains(x))||images.Length==0||images.Any(x=>!ImageExtensions.Contains(x)))return Bad("Only approved resume and image extensions are allowed.");return await Save(a,"uploads",new UploadSettingsDto(r.MaximumResumeSizeMb,resumes,r.MaximumProfileImageSizeMb,images),"UploadSettingsUpdated",AuditSeverity.Information,t);}
 public async Task<SystemSettingsMutationResult> UpdateSecurityAsync(int a,UpdateSecuritySettingsRequest r,CancellationToken t=default){if(r.MinimumPasswordLength is <8 or >128||r.MaximumFailedLoginAttempts is <3 or >20||r.AccountLockoutMinutes is <1 or >1440||r.SessionTimeoutMinutes is <5 or >1440)return Bad("Security values are outside their safe ranges.");return await Save(a,"security",new SecuritySettingsDto(r.MinimumPasswordLength,r.RequireUppercase,r.RequireLowercase,r.RequireNumber,r.RequireSpecialCharacter,r.MaximumFailedLoginAttempts,r.AccountLockoutMinutes,r.SessionTimeoutMinutes),"SecuritySettingsUpdated",AuditSeverity.Warning,t);}
 public Task<SystemSettingsMutationResult> UpdateNotificationsAsync(int a,UpdateNotificationSettingsRequest r,CancellationToken t=default)=>Save(a,"notifications",new NotificationSettingsDto(r.EnableNotifications,r.NotifyCandidateOnStatusChange,r.NotifyRecruiterOnNewApplication,r.NotifyManagerOnEvaluationRequired,r.NotifyParticipantsOnInterviewChange),"NotificationSettingsUpdated",AuditSeverity.Information,t);
 public async Task<SystemSettingsMutationResult> UpdateMaintenanceAsync(int a,UpdateMaintenanceSettingsRequest r,CancellationToken t=default){if(r.MaintenanceModeEnabled&&string.IsNullOrWhiteSpace(r.MaintenanceMessage))return Bad("A maintenance message is required.");if(r.MaintenanceModeEnabled&&!r.AllowAdminLoginDuringMaintenance)return new(false,null,"Admin recovery access must remain enabled.",true);return await Save(a,"maintenance",new MaintenanceSettingsDto(r.MaintenanceModeEnabled,r.MaintenanceMessage.Trim(),true),"MaintenanceSettingsUpdated",r.MaintenanceModeEnabled?AuditSeverity.Warning:AuditSeverity.Information,t);}
 public async Task<SystemSettingsMutationResult> ResetAsync(int a,string section,CancellationToken t=default){if(!SystemSettingKeys.Sections.ContainsKey(section))return Bad("Unsupported settings section.");var old=await provider.GetAsync(t);var value=await provider.ResetSectionAsync(section,a,t);await audit.WriteAsync(new(a,"SystemSettingsSectionReset","SystemSetting",null,section,$"Reset {section} settings.",AuditSeverity.Information,true,Section(old,section),value,new{section}),t);return new(true,value);}
 async Task<SystemSettingsMutationResult> Save(int a,string section,object value,string action,AuditSeverity severity,CancellationToken t){var old=Section(await provider.GetAsync(t),section);await provider.UpdateSectionAsync(section,value,a,t);await audit.WriteAsync(new(a,action,"SystemSetting",null,section,$"Updated {section} settings.",severity,true,old,value,new{section}),t);return new(true,value);}
 static object Section(SystemSettingsDto x,string s)=>s switch{"general"=>x.General,"recruitment"=>x.Recruitment,"uploads"=>x.Uploads,"security"=>x.Security,"notifications"=>x.Notifications,_=>x.Maintenance};
 static string[] Normalize(IEnumerable<string> xs)=>xs.Select(x=>x.Trim().ToLowerInvariant()).Where(x=>x.Length>0).Select(x=>x.StartsWith('.')?x:"."+x).Distinct().ToArray();static SystemSettingsMutationResult Bad(string e)=>new(false,null,e);
}
