using JobOrbit.Application.DTOs.HiringManagerSettings;using JobOrbit.Application.Interfaces;using JobOrbit.Domain.Entities;using JobOrbit.Domain.Enums;using Microsoft.AspNetCore.Identity;
namespace JobOrbit.Application.Services;
public sealed class HiringManagerSettingsService(IHiringManagerSettingsRepository repository,IPasswordHasher<User>hasher,IAuditService audit):IHiringManagerSettingsService
{
 async Task<HiringManagerProfile?>Profile(int id,CancellationToken t){var x=await repository.GetAsync(id,t);return x?.User.Role==UserRole.HiringManager?x:null;}static string?Clean(string?v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();static HiringManagerSettingsDto Map(HiringManagerProfile x)=>new(){Email=x.User.Email,FirstName=x.User.FirstName,LastName=x.User.LastName,Phone=x.PhoneNumber,JobTitle=x.JobTitle,DepartmentName=x.Department?.Name,OrganizationName=x.Organization.Name,CandidateReviewNotifications=x.CandidateReviewNotifications,InterviewNotifications=x.InterviewNotifications,EvaluationNotifications=x.EvaluationNotifications,DecisionNotifications=x.DecisionNotifications,EmailNotifications=x.EmailNotifications};
 public async Task<HiringManagerSettingsDto?>GetAsync(int id,CancellationToken t=default){var x=await Profile(id,t);return x is null?null:Map(x);}
 public async Task<HiringManagerSettingsDto?>UpdateAsync(int id,UpdateHiringManagerSettingsRequest r,CancellationToken t=default){var x=await Profile(id,t);if(x is null)return null;x.User.FirstName=r.FirstName.Trim();x.User.LastName=r.LastName.Trim();x.PhoneNumber=Clean(r.Phone);x.CandidateReviewNotifications=r.CandidateReviewNotifications;x.InterviewNotifications=r.InterviewNotifications;x.EvaluationNotifications=r.EvaluationNotifications;x.DecisionNotifications=r.DecisionNotifications;x.EmailNotifications=r.EmailNotifications;await repository.SaveAsync(t);return Map(x);}
 public async Task<HiringManagerPasswordOutcome>ChangePasswordAsync(int id,ChangeHiringManagerPasswordRequest r,CancellationToken t=default){var x=await Profile(id,t);if(x is null)return HiringManagerPasswordOutcome.NotFound;if(hasher.VerifyHashedPassword(x.User,x.User.PasswordHash,r.CurrentPassword)==PasswordVerificationResult.Failed)return HiringManagerPasswordOutcome.IncorrectCurrentPassword;x.User.PasswordHash=hasher.HashPassword(x.User,r.NewPassword);await audit.WriteAsync(new JobOrbit.Application.Auditing.AuditEvent(id,"PasswordChanged",nameof(User),id,x.User.Email,"Hiring manager changed their password."),t);return HiringManagerPasswordOutcome.Changed;}
}
