using System.Text.Json;using System.Text.Json.Nodes;using JobOrbit.Application.Auditing;using JobOrbit.Application.DTOs.AdminAuditLogs;using JobOrbit.Application.DTOs.Jobs;using JobOrbit.Application.Interfaces;using JobOrbit.Domain.Enums;using Microsoft.EntityFrameworkCore;
namespace JobOrbit.Infrastructure.Persistence.Repositories;
public sealed class AdminAuditLogRepository(JobOrbitDbContext db):IAdminAuditLogRepository
{
 public async Task<AdminAuditLogListResult>ListAsync(AdminAuditLogQuery q,CancellationToken t=default)
 {
  if(q.From.HasValue&&q.To.HasValue&&q.From>q.To)return new(false,null,"Invalid date range");if(!string.IsNullOrWhiteSpace(q.Action)&&!AuditCatalog.Actions.ContainsKey(q.Action))return new(false,null,"Invalid audit action");if(!string.IsNullOrWhiteSpace(q.EntityType)&&!AuditCatalog.EntityTypes.ContainsKey(q.EntityType))return new(false,null,"Invalid entity type");if(!string.IsNullOrWhiteSpace(q.Severity)&&!Enum.TryParse<AuditSeverity>(q.Severity,true,out _))return new(false,null,"Invalid severity");if(!string.IsNullOrWhiteSpace(q.ActorRole)&&!JobOrbit.Application.Authorization.PermissionConstants.TryRole(q.ActorRole,out _))return new(false,null,"Invalid actor role");
  var rows=db.AuditLogs.AsNoTracking();if(!string.IsNullOrWhiteSpace(q.Search)){var s=q.Search.Trim();rows=rows.Where(x=>(x.ActorNameSnapshot!=null&&x.ActorNameSnapshot.Contains(s))||(x.User!=null&&((x.User.FirstName+" "+x.User.LastName).Contains(s)||x.User.Email.Contains(s)))||x.Action.Contains(s)||(x.EntityDisplayName!=null&&x.EntityDisplayName.Contains(s))||(x.Description!=null&&x.Description.Contains(s))||(x.CorrelationId!=null&&x.CorrelationId.Contains(s)));}if(!string.IsNullOrWhiteSpace(q.Action))rows=rows.Where(x=>x.Action==q.Action);if(!string.IsNullOrWhiteSpace(q.EntityType))rows=rows.Where(x=>x.EntityName==q.EntityType);if(q.EntityId.HasValue)rows=rows.Where(x=>x.EntityId==q.EntityId);if(q.ActorUserId.HasValue)rows=rows.Where(x=>x.UserId==q.ActorUserId);if(!string.IsNullOrWhiteSpace(q.ActorRole)){JobOrbit.Application.Authorization.PermissionConstants.TryRole(q.ActorRole,out var role);rows=rows.Where(x=>x.ActorRoleSnapshot==q.ActorRole||(x.User!=null&&x.User.Role==role));}if(!string.IsNullOrWhiteSpace(q.Severity)){var severity=Enum.Parse<AuditSeverity>(q.Severity,true);rows=rows.Where(x=>x.Severity==severity);}if(q.IsSuccess.HasValue)rows=rows.Where(x=>x.IsSuccess==q.IsSuccess);if(q.From.HasValue)rows=rows.Where(x=>x.CreatedAt>=q.From);if(q.To.HasValue)rows=rows.Where(x=>x.CreatedAt<=q.To);rows=q.Sort.Equals("oldest",StringComparison.OrdinalIgnoreCase)?rows.OrderBy(x=>x.CreatedAt):rows.OrderByDescending(x=>x.CreatedAt);
  var total=await rows.CountAsync(t);var raw=await rows.Skip((q.Page-1)*q.PageSize).Take(q.PageSize).Select(x=>new{x.Id,x.UserId,Actor=x.ActorNameSnapshot??(x.User==null?"System":x.User.FirstName+" "+x.User.LastName),Role=x.ActorRoleSnapshot??(x.User==null?null:x.User.Role.ToString()),x.Action,x.EntityName,x.EntityId,x.EntityDisplayName,Description=x.Description??(x.Action+" on "+x.EntityName),x.Severity,x.IsSuccess,x.IpAddress,x.CreatedAt}).ToListAsync(t);var items=raw.Select(x=>new AdminAuditLogListItemDto(x.Id,x.UserId,x.Actor,x.Role,x.Action,AuditCatalog.Actions.TryGetValue(x.Action,out var a)?a.Label:Words(x.Action),x.EntityName,x.EntityId,x.EntityDisplayName,x.Description,x.Severity.ToString(),x.IsSuccess,x.IpAddress,x.CreatedAt)).ToList();return new(true,new PagedResultDto<AdminAuditLogListItemDto>{Items=items,Page=q.Page,PageSize=q.PageSize,TotalItems=total,TotalPages=(int)Math.Ceiling(total/(double)q.PageSize)});
 }
 public async Task<AdminAuditLogDetailsDto?>DetailsAsync(int id,CancellationToken t=default)
 {
  var x=await db.AuditLogs.AsNoTracking().Where(x=>x.Id==id).Select(x=>new{x.Id,x.UserId,Actor=x.ActorNameSnapshot??(x.User==null?"System":x.User.FirstName+" "+x.User.LastName),Role=x.ActorRoleSnapshot??(x.User==null?null:x.User.Role.ToString()),x.Action,x.EntityName,x.EntityId,x.EntityDisplayName,Description=x.Description??(x.Action+" on "+x.EntityName),x.Severity,x.IsSuccess,x.OldValues,x.NewValues,x.Metadata,x.IpAddress,x.UserAgent,x.CorrelationId,x.CreatedAt}).SingleOrDefaultAsync(t);return x is null?null:new(x.Id,new(x.UserId,x.Actor,x.Role),x.Action,AuditCatalog.Actions.TryGetValue(x.Action,out var a)?a.Label:Words(x.Action),x.EntityName,x.EntityId,x.EntityDisplayName,x.Description,x.Severity.ToString(),x.IsSuccess,Parse(x.OldValues),Parse(x.NewValues),Parse(x.Metadata),x.IpAddress,x.UserAgent,x.CorrelationId,x.CreatedAt);
 }
 static object?Parse(string? value){if(string.IsNullOrWhiteSpace(value))return null;try{var n=JsonNode.Parse(value);Mask(n);return JsonSerializer.Deserialize<object>(n!.ToJsonString());}catch{return new{value="Stored value could not be parsed safely."};}}
 static readonly string[] Secrets=["password","hash","token","connectionstring","storedfilename","physicalpath","secret"];static void Mask(JsonNode?node){if(node is JsonObject o)foreach(var k in o.Select(x=>x.Key).ToList()){if(Secrets.Any(s=>k.Contains(s,StringComparison.OrdinalIgnoreCase)))o[k]="[REDACTED]";else Mask(o[k]);}else if(node is JsonArray a)foreach(var n in a)Mask(n);}static string Words(string x)=>System.Text.RegularExpressions.Regex.Replace(x,"([a-z])([A-Z])","$1 $2");
}
