using JobOrbit.Application.DTOs.HiringManagerInterviews;using JobOrbit.Application.DTOs.Jobs;using JobOrbit.Application.Interfaces;using JobOrbit.Domain.Entities;using JobOrbit.Domain.Enums;using Microsoft.EntityFrameworkCore;
namespace JobOrbit.Infrastructure.Persistence.Repositories;
public sealed class HiringManagerInterviewRepository(JobOrbitDbContext db):IHiringManagerInterviewRepository
{
 async Task<(int Org,int? Dept)?>Scope(int id,CancellationToken t){var x=await db.HiringManagerProfiles.AsNoTracking().Where(x=>x.UserId==id&&x.User.IsActive&&x.User.Role==UserRole.HiringManager).Select(x=>new{x.OrganizationId,x.DepartmentId}).SingleOrDefaultAsync(t);return x is null?null:(x.OrganizationId,x.DepartmentId);}
 IQueryable<Interview>Scoped((int Org,int? Dept)s)=>db.Interviews.Where(x=>x.JobApplication.JobPosting.OrganizationId==s.Org&&(!s.Dept.HasValue||x.JobApplication.JobPosting.DepartmentId==s.Dept));
 public async Task<PagedResultDto<HiringManagerInterviewListItemDto>>ListAsync(int id,HiringManagerInterviewQuery query,CancellationToken t=default){var s=await Scope(id,t);if(s is null)return new(){Page=query.Page,PageSize=query.PageSize};var q=Scoped(s.Value).AsNoTracking();if(!string.IsNullOrWhiteSpace(query.Status)&&Enum.TryParse<InterviewStatus>(query.Status,true,out var status))q=q.Where(x=>x.Status==status);else if(query.Sort.Equals("upcoming",StringComparison.OrdinalIgnoreCase))q=q.Where(x=>x.Status==InterviewStatus.Scheduled||x.Status==InterviewStatus.Rescheduled);if(query.JobId.HasValue)q=q.Where(x=>x.JobApplication.JobPostingId==query.JobId);if(query.From.HasValue)q=q.Where(x=>x.ScheduledAt>=query.From.Value.ToUniversalTime());if(query.To.HasValue)q=q.Where(x=>x.ScheduledAt<=query.To.Value.ToUniversalTime());if(!string.IsNullOrWhiteSpace(query.Search)){var term=query.Search.Trim();q=q.Where(x=>(x.JobApplication.CandidateProfile.User.FirstName+" "+x.JobApplication.CandidateProfile.User.LastName).Contains(term)||x.JobApplication.JobPosting.Title.Contains(term)||x.JobApplication.JobPosting.Organization.Name.Contains(term)||(x.Location??"").Contains(term));}q=query.Sort.ToLowerInvariant()switch{"latest"=>q.OrderByDescending(x=>x.ScheduledAt),"oldest"=>q.OrderBy(x=>x.CreatedAt),_=>q.OrderBy(x=>x.ScheduledAt<DateTime.UtcNow).ThenBy(x=>x.ScheduledAt)};var total=await q.CountAsync(t);var items=await q.Skip((query.Page-1)*query.PageSize).Take(query.PageSize).Select(x=>new HiringManagerInterviewListItemDto{InterviewId=x.Id,ApplicationId=x.JobApplicationId,CandidateId=x.JobApplication.CandidateProfileId,CandidateName=x.JobApplication.CandidateProfile.User.FirstName+" "+x.JobApplication.CandidateProfile.User.LastName,ProfessionalTitle=x.JobApplication.CandidateProfile.Headline,JobId=x.JobApplication.JobPostingId,JobTitle=x.JobApplication.JobPosting.Title,OrganizationName=x.JobApplication.JobPosting.Organization.Name,ScheduledAt=x.ScheduledAt,DurationMinutes=x.DurationMinutes,Location=x.Location,MeetingLink=x.MeetingUrl,Status=x.Status.ToString(),ApplicationStatus=x.JobApplication.Status.ToString()}).ToListAsync(t);return new(){Items=items,Page=query.Page,PageSize=query.PageSize,TotalItems=total,TotalPages=(int)Math.Ceiling(total/(double)query.PageSize)};}
 public async Task<HiringManagerInterviewDetailsDto?>DetailsAsync(int id,int interviewId,CancellationToken t=default){var s=await Scope(id,t);if(s is null)return null;return await Scoped(s.Value).AsNoTracking().Where(x=>x.Id==interviewId).Select(x=>new HiringManagerInterviewDetailsDto{InterviewId=x.Id,ApplicationId=x.JobApplicationId,Candidate=new(){CandidateId=x.JobApplication.CandidateProfileId,FullName=x.JobApplication.CandidateProfile.User.FirstName+" "+x.JobApplication.CandidateProfile.User.LastName,Email=x.JobApplication.CandidateProfile.User.Email,Phone=x.JobApplication.CandidateProfile.PhoneNumber,ProfessionalTitle=x.JobApplication.CandidateProfile.Headline,Skills=x.JobApplication.CandidateProfile.CandidateSkills.Select(s=>s.Skill.Name).ToList()},Job=new(){JobId=x.JobApplication.JobPostingId,Title=x.JobApplication.JobPosting.Title,OrganizationName=x.JobApplication.JobPosting.Organization.Name,DepartmentName=x.JobApplication.JobPosting.Department.Name},ScheduledAt=x.ScheduledAt,DurationMinutes=x.DurationMinutes,Location=x.Location,MeetingLink=x.MeetingUrl,Status=x.Status.ToString(),ApplicationStatus=x.JobApplication.Status.ToString(),Notes=null,CreatedAt=x.CreatedAt,UpdatedAt=x.UpdatedAt}).SingleOrDefaultAsync(t);}
}
