import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import DashboardLayout from '../components/dashboard/DashboardLayout'
import AdminSidebar from '../components/admin/AdminSidebar'
import AdminNavbar from '../components/admin/AdminNavbar'
import { useAuth } from '../context/AuthContext'
import { createAdminUser, getAdminUser, updateAdminUser } from '../services/adminUserService'
import { getOrganizationLookup } from '../services/adminOrganizationService'
import { getDepartmentLookup } from '../services/adminDepartmentService'
import styles from './AdminUsers.module.css'

const initial={firstName:'',lastName:'',email:'',phone:'',role:'Candidate',organizationId:'',departmentId:'',temporaryPassword:'',confirmPassword:'',isActive:true}
export default function AdminUserForm({edit=false}) {
  const {userId}=useParams(),{user,logout}=useAuth(),navigate=useNavigate()
  const [open,setOpen]=useState(false),[form,setForm]=useState(initial),[organizations,setOrganizations]=useState([]),[departments,setDepartments]=useState([]),[departmentsLoading,setDepartmentsLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>{getOrganizationLookup(edit).then(setOrganizations).catch(()=>setError('Could not load organizations.'))},[edit])
  useEffect(()=>{if(edit)getAdminUser(userId).then(x=>setForm({...x,organizationId:x.organizationId||'',departmentId:x.departmentId||''})).catch(()=>setError('Could not load user.'))},[edit,userId])
  useEffect(()=>{if(!form.organizationId){setDepartments([]);return}setDepartmentsLoading(true);getDepartmentLookup(form.organizationId,edit).then(setDepartments).catch(()=>setError('Could not load departments.')).finally(()=>setDepartmentsLoading(false))},[form.organizationId,edit])
  const set=(key,value)=>setForm(x=>({...x,[key]:value}))
  async function submit(event){event.preventDefault();if(!edit&&form.temporaryPassword!==form.confirmPassword){setError('Passwords must match.');return}setBusy(true);setError('');try{const payload={...form,organizationId:form.organizationId?Number(form.organizationId):null,departmentId:form.departmentId?Number(form.departmentId):null};const saved=edit?await updateAdminUser(userId,payload):await createAdminUser(payload);navigate(`/admin/users/${saved.userId}`)}catch(e){setError(e.response?.data?.title||Object.values(e.response?.data?.errors||{})[0]?.[0]||'Could not save user.')}finally{setBusy(false)}}
  const scoped=form.role==='Recruiter'||form.role==='HiringManager'
  return <DashboardLayout sidebar={<AdminSidebar isOpen={open} onClose={()=>setOpen(false)} onLogout={()=>{logout();navigate('/login')}}/>} navbar={<AdminNavbar user={user} onMenuClick={()=>setOpen(true)}/>}><button className={styles.back} onClick={()=>navigate('/admin/users')}>← Back to Users</button><form className={styles.form} onSubmit={submit}><h1>{edit?'Edit User':'Add User'}</h1><div><label>First name<input required maxLength="100" value={form.firstName} onChange={e=>set('firstName',e.target.value)}/></label><label>Last name<input required maxLength="100" value={form.lastName} onChange={e=>set('lastName',e.target.value)}/></label><label>Email<input required type="email" disabled={edit} value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Phone<input maxLength="30" value={form.phone||''} onChange={e=>set('phone',e.target.value)}/></label><label>Role<select disabled={edit} value={form.role} onChange={e=>set('role',e.target.value)}>{['Candidate','Recruiter','HiringManager','Admin'].map(x=><option key={x}>{x}</option>)}</select></label>{scoped&&<label>Organization<select required value={form.organizationId} onChange={e=>setForm(x=>({...x,organizationId:e.target.value,departmentId:''}))}><option value="">Select organization</option>{organizations.map(x=><option key={x.organizationId} value={x.organizationId} disabled={!x.isActive&&Number(form.organizationId)!==x.organizationId}>{x.name} ({x.code}){x.isActive?'':' — Inactive'}</option>)}</select></label>}{form.role==='HiringManager'&&<label>Department<select disabled={!form.organizationId||departmentsLoading} value={form.departmentId} onChange={e=>set('departmentId',e.target.value)}><option value="">{departmentsLoading?'Loading departments…':departments.length?'Select department':'No active departments'}</option>{departments.map(x=><option key={x.departmentId} value={x.departmentId} disabled={!x.isActive&&Number(form.departmentId)!==x.departmentId}>{x.name} ({x.code}){x.isActive?'':' — Inactive'}</option>)}</select></label>}{!edit&&<><label>Temporary password<input required minLength="10" type="password" value={form.temporaryPassword} onChange={e=>set('temporaryPassword',e.target.value)}/></label><label>Confirm password<input required type="password" value={form.confirmPassword} onChange={e=>set('confirmPassword',e.target.value)}/></label><label><input type="checkbox" checked={form.isActive} onChange={e=>set('isActive',e.target.checked)}/> Active account</label></>}</div>{error&&<p className={styles.error}>{error}</p>}<button disabled={busy}>{busy?'Saving…':edit?'Save Changes':'Create User'}</button></form></DashboardLayout>
}
