import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Sidebar from '../components/candidate/Sidebar'; import TopNavbar from '../components/candidate/TopNavbar'; import DashboardLayout from '../components/dashboard/DashboardLayout'; import { useAuth } from '../context/AuthContext'
import { deleteResume, downloadResume, getResumes, setDefaultResume, uploadResume } from '../services/candidateResumeService'; import styles from './CandidateResume.module.css'

const formatSize = (bytes) => `${(bytes / 1024 / 1024).toFixed(2)} MB`; const formatDate = (value) => new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value))
export default function CandidateResume() {
  const [open,setOpen]=useState(false),[items,setItems]=useState([]),[state,setState]=useState('loading'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[file,setFile]=useState(null),[name,setName]=useState(''),[progress,setProgress]=useState(0); const input=useRef(); const navigate=useNavigate(); const {logout,user}=useAuth()
  const load=useCallback(async(signal)=>{setState('loading');try{setItems(await getResumes(signal));setState('ready')}catch(e){if(e.name!=='CanceledError')setState('error')}},[]); useEffect(()=>{const c=new AbortController();load(c.signal);return()=>c.abort()},[load])
  const choose=(candidate)=>{setMessage('');if(!candidate)return;if(candidate.size>5*1024*1024||!(/\.(pdf|doc|docx)$/i.test(candidate.name))){setMessage('Choose a PDF, DOC, or DOCX file up to 5 MB.');return}setFile(candidate);setName(candidate.name.replace(/\.[^.]+$/,''))}
  const submit=async()=>{if(!file||busy)return;setBusy(true);setProgress(0);setMessage('');try{await uploadResume(file,name,setProgress);setFile(null);setName('');setMessage('Resume uploaded successfully.');await load()}catch(e){setMessage(e.response?.data?.detail||'Upload failed. Please try again.')}finally{setBusy(false)}}
  const action=async(fn)=>{setBusy(true);setMessage('');try{await fn();await load()}catch(e){setMessage(e.response?.data?.detail||'Action could not be completed.')}finally{setBusy(false)}}; const logoutUser=()=>{logout();navigate('/login',{replace:true})}
  return <DashboardLayout sidebar={<Sidebar isOpen={open} onClose={()=>setOpen(false)} onLogout={logoutUser}/>} navbar={<TopNavbar onMenuClick={()=>setOpen(true)} user={user}/>}><header className={styles.header}><h1>My Resume</h1><p>Manage the resumes you use for job applications.</p></header><section className={styles.upload} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}><strong>Drag and drop your resume here</strong><p>PDF, DOC, or DOCX · Maximum 5 MB</p><button type="button" onClick={()=>input.current.click()}>Browse Files</button><input ref={input} hidden type="file" accept=".pdf,.doc,.docx" onChange={e=>choose(e.target.files[0])}/>{file&&<div className={styles.selected}><input value={name} maxLength="200" onChange={e=>setName(e.target.value)} aria-label="Resume display name"/><span>{file.name}</span><button type="button" disabled={busy} onClick={submit}>{busy?`Uploading ${progress}%`:'Upload Resume'}</button></div>}</section>{message&&<div className={styles.message}>{message}</div>}<section className={styles.list}><h2>Saved Resumes</h2>{state==='loading'&&<div className={styles.skeleton}/>} {state==='error'&&<div className={styles.empty}>Could not load resumes.<button onClick={()=>load()} type="button">Retry</button></div>}{state==='ready'&&!items.length&&<div className={styles.empty}>No resumes uploaded yet.</div>}{state==='ready'&&items.map(r=><article key={r.resumeId}><div><strong>{r.displayName}</strong><span>{r.originalFileName} · {formatSize(r.sizeBytes)} · {formatDate(r.uploadedOn)}</span></div>{r.isDefault&&<b>Default</b>}<div className={styles.actions}>{!r.isDefault&&<button disabled={busy} onClick={()=>action(()=>setDefaultResume(r.resumeId))}>Set Default</button>}<button disabled={busy} onClick={()=>downloadResume(r)}>Download</button><button disabled={busy} className={styles.delete} onClick={()=>{if(confirm(`Delete ${r.displayName}?`))action(()=>deleteResume(r.resumeId))}}>Delete</button></div></article>)}</section></DashboardLayout>
}
