import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import Sidebar from '../components/candidate/Sidebar'
import TopNavbar from '../components/candidate/TopNavbar'
import DashboardLayout from '../components/dashboard/DashboardLayout'
import { useAuth } from '../context/AuthContext'
import { changeCandidatePassword, getCandidateSettings, updateCandidateSettings } from '../services/candidateSettingsService'
import styles from './CandidateSettings.module.css'

const preferenceFields=[['emailNotifications','Email notifications','Receive important JobOrbit emails.'],['applicationStatusNotifications','Application status updates','Know when an application moves forward.'],['interviewReminders','Interview reminders','Receive reminders for scheduled interviews.'],['jobRecommendationNotifications','Job recommendations','Hear about newly recommended opportunities.']]
export default function CandidateSettings(){
  const [open,setOpen]=useState(false),[settings,setSettings]=useState(null),[state,setState]=useState('loading'),[message,setMessage]=useState(''),[passwords,setPasswords]=useState({currentPassword:'',newPassword:'',confirmNewPassword:''}),[show,setShow]=useState(false),[passwordBusy,setPasswordBusy]=useState(false);const {logout,user}=useAuth();const navigate=useNavigate()
  const load=useCallback(async(signal)=>{setState('loading');setMessage('');try{setSettings(await getCandidateSettings(signal));setState('ready')}catch(e){if(e.name!=='CanceledError')setState('error')}},[]);useEffect(()=>{const c=new AbortController();load(c.signal);return()=>c.abort()},[load])
  const logoutUser=()=>{logout();navigate('/login',{replace:true})}
  async function savePreferences(e){e.preventDefault();if(state==='saving')return;setState('saving');setMessage('');try{setSettings(await updateCandidateSettings(Object.fromEntries(preferenceFields.map(([key])=>[key,settings[key]]))));setMessage('Preferences saved successfully.')}catch(error){setMessage(error.response?.data?.detail||'Unable to save preferences.')}finally{setState('ready')}}
  async function changePassword(e){e.preventDefault();if(passwordBusy)return;setMessage('');if(passwords.newPassword!==passwords.confirmNewPassword){setMessage('New password and confirmation must match.');return}setPasswordBusy(true);try{await changeCandidatePassword(passwords);setPasswords({currentPassword:'',newPassword:'',confirmNewPassword:''});setMessage('Password changed successfully.')}catch(error){setMessage(error.response?.data?.title||error.response?.data?.detail||'Unable to change password.')}finally{setPasswordBusy(false)}}
  return <DashboardLayout sidebar={<Sidebar isOpen={open} onClose={()=>setOpen(false)} onLogout={logoutUser}/>} navbar={<TopNavbar onMenuClick={()=>setOpen(true)} user={user}/>}><header className={styles.header}><h1>Settings</h1><p>Manage notifications, security, and account information.</p></header>{state==='loading'&&<div className={styles.skeleton}/>} {state==='error'&&<div className={styles.errorState}>Could not load settings.<button onClick={()=>load()} type="button">Retry</button></div>}{settings&&state!=='loading'&&<div className={styles.sections}><form className={styles.card} onSubmit={savePreferences}><h2>Notification Preferences</h2><p>Choose which updates you want to receive.</p><div className={styles.preferences}>{preferenceFields.map(([key,label,description])=><label key={key}><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={settings[key]} onChange={e=>setSettings(current=>({...current,[key]:e.target.checked}))}/><i aria-hidden="true"/></label>)}</div><button disabled={state==='saving'}>{state==='saving'?'Saving…':'Save Preferences'}</button></form><form className={styles.card} onSubmit={changePassword}><h2>Security</h2><p>Use at least 10 characters with uppercase, lowercase, and a number.</p><div className={styles.passwordGrid}>{[['currentPassword','Current password'],['newPassword','New password'],['confirmNewPassword','Confirm new password']].map(([key,label])=><label key={key}>{label}<input required minLength={key==='currentPassword'?1:10} maxLength="128" type={show?'text':'password'} value={passwords[key]} onChange={e=>setPasswords(current=>({...current,[key]:e.target.value}))}/></label>)}</div><label className={styles.show}><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Show passwords</label><button disabled={passwordBusy}>{passwordBusy?'Changing…':'Change Password'}</button></form><section className={styles.card}><h2>Account Information</h2><p>Your login email is read-only here.</p><label className={styles.email}>Email<input disabled value={settings.email}/></label><Link to="/candidate/profile">Update personal information in My Profile</Link></section>{message&&<div className={message.includes('successfully')?styles.success:styles.error} role="status">{message}</div>}</div>}</DashboardLayout>
}
