import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import DashboardLayout from '../components/dashboard/DashboardLayout'
import ManagerSidebar from '../components/manager/ManagerSidebar'
import ManagerNavbar from '../components/manager/ManagerNavbar'
import { useAuth } from '../context/AuthContext'
import { getHiringManagerCandidate } from '../services/hiringManagerCandidateService'
import { createManagerEvaluation, getManagerEvaluations, updateManagerEvaluation } from '../services/hiringManagerEvaluationService'
import baseStyles from './HiringManagerCandidates.module.css'
import formStyles from './HiringManagerEvaluation.module.css'

const styles = { ...baseStyles, ...formStyles }

const initial = { technicalScore: 5, communicationScore: 5, experienceScore: 5, cultureFitScore: 5, overallComments: '', recommendation: 'Hold' }
export default function HiringManagerEvaluation() {
  const { applicationId } = useParams(), navigate = useNavigate(), { user, logout } = useAuth()
  const [open, setOpen] = useState(false), [candidate, setCandidate] = useState(null), [evaluationId, setEvaluationId] = useState(null), [form, setForm] = useState(initial), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const load = useCallback(async () => { const c = new AbortController(); setLoading(true); setError(''); try { const [details, evaluations] = await Promise.all([getHiringManagerCandidate(applicationId, c.signal), getManagerEvaluations(applicationId, c.signal)]); setCandidate(details); const own = evaluations.find(x => x.canEdit); if (own) { setEvaluationId(own.evaluationId); setForm({ technicalScore: own.technicalScore, communicationScore: own.communicationScore, experienceScore: own.experienceScore, cultureFitScore: own.cultureFitScore, overallComments: own.overallComments || '', recommendation: own.recommendation }) } } catch (e) { if (e.name !== 'CanceledError') setError(e.response?.status === 404 ? 'Candidate not found or outside your scope.' : 'Could not load evaluation.') } finally { setLoading(false) } return () => c.abort() }, [applicationId])
  useEffect(() => { load() }, [load])
  const overall = useMemo(() => ((+form.technicalScore + +form.communicationScore + +form.experienceScore + +form.cultureFitScore) / 4).toFixed(2), [form])
  const set = (key, value) => setForm(x => ({ ...x, [key]: value }))
  const submit = async e => { e.preventDefault(); setError(''); setSuccess(''); const scores = ['technicalScore', 'communicationScore', 'experienceScore', 'cultureFitScore']; if (scores.some(key => form[key] < 1 || form[key] > 10)) { setError('All scores must be between 1 and 10.'); return } setSaving(true); try { const payload = { ...form, ...Object.fromEntries(scores.map(key => [key, Number(form[key])])) }; const saved = evaluationId ? await updateManagerEvaluation(evaluationId, payload) : await createManagerEvaluation(applicationId, payload); setEvaluationId(saved.evaluationId); setSuccess(evaluationId ? 'Evaluation updated successfully.' : 'Evaluation submitted successfully.') } catch (e) { setError(e.response?.data?.title || 'Could not save evaluation.') } finally { setSaving(false) } }
  const signOut = () => { logout(); navigate('/login') }
  return <DashboardLayout sidebar={<ManagerSidebar isOpen={open} onClose={() => setOpen(false)} onLogout={signOut} />} navbar={<ManagerNavbar user={user} onMenuClick={() => setOpen(true)} />}><button className={styles.back} onClick={() => navigate(`/manager/candidates/${applicationId}`)}>← Back to Candidate</button>{loading ? <div className={styles.state}>Loading evaluation…</div> : error && !candidate ? <div className={styles.state}>{error}<button onClick={load}>Retry</button></div> : candidate && <><header className={styles.heading}><h1>{evaluationId ? 'Edit Candidate Evaluation' : 'Evaluate Candidate'}</h1><p>{candidate.candidate.fullName} · {candidate.job.title}</p></header><form className={styles.evaluationForm} onSubmit={submit}><section><h2>Candidate Scoring</h2><div className={styles.scoreGrid}>{[['technicalScore','Technical Skill'],['communicationScore','Communication'],['experienceScore','Experience'],['cultureFitScore','Culture Fit']].map(([key,label]) => <label key={key}>{label}<span>1–10</span><input type="number" min="1" max="10" required value={form[key]} onChange={e => set(key, e.target.value)} /></label>)}</div><div className={styles.overall}>Calculated Overall Score <strong>{overall}/10</strong></div><label>Overall Comments<textarea maxLength="4000" rows="6" value={form.overallComments} onChange={e => set('overallComments', e.target.value)} /></label><label>Recommendation<select value={form.recommendation} onChange={e => set('recommendation', e.target.value)}><option>Proceed</option><option>Hold</option><option>Reject</option></select></label>{error && <div className={styles.error}>{error}</div>}{success && <div className={styles.success}>{success}</div>}<div className={styles.formActions}><button type="button" onClick={() => navigate(`/manager/candidates/${applicationId}`)}>Cancel</button><button disabled={saving} type="submit">{saving ? 'Saving…' : evaluationId ? 'Save Changes' : 'Submit Evaluation'}</button></div></section></form></>}</DashboardLayout>
}
