import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import DashboardLayout from '../components/dashboard/DashboardLayout'
import ManagerSidebar from '../components/manager/ManagerSidebar'
import ManagerNavbar from '../components/manager/ManagerNavbar'
import { useAuth } from '../context/AuthContext'
import { downloadHiringManagerResume, getHiringManagerCandidate } from '../services/hiringManagerCandidateService'
import styles from './HiringManagerCandidates.module.css'

export default function HiringManagerCandidateDetails() {
  const { applicationId } = useParams(), [open, setOpen] = useState(false), [data, setData] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const { user, logout } = useAuth(), navigate = useNavigate()
  const load = useCallback(() => { const c = new AbortController(); setLoading(true); setError(''); getHiringManagerCandidate(applicationId, c.signal).then(setData).catch(e => { if (e.name !== 'CanceledError') setError(e.response?.status === 404 ? 'Application not found or outside your assigned scope.' : 'Could not load this candidate.') }).finally(() => setLoading(false)); return () => c.abort() }, [applicationId])
  useEffect(() => load(), [load])
  const download = async () => { try { const { blob, fileName } = await downloadHiringManagerResume(applicationId), url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = fileName; link.click(); URL.revokeObjectURL(url) } catch { setError('Resume download failed.') } }
  const signOut = () => { logout(); navigate('/login') }
  return <DashboardLayout sidebar={<ManagerSidebar isOpen={open} onClose={() => setOpen(false)} onLogout={signOut} />} navbar={<ManagerNavbar user={user} onMenuClick={() => setOpen(true)} />}><button className={styles.back} onClick={() => navigate('/manager/candidates')}>← Back to Candidates</button>{loading ? <div className={styles.state}>Loading candidate…</div> : error && !data ? <div className={styles.state}>{error}<button onClick={load}>Retry</button></div> : data && <><header className={styles.detailHeader}><div><span className={styles.badge}>{data.status}</span><h1>{data.candidate.fullName}</h1><p>{data.candidate.professionalTitle || 'Candidate'} · {data.job.title}</p></div><div className={styles.actions}><button onClick={() => navigate(`/manager/candidates/${applicationId}/evaluate`)}>Evaluate Candidate</button>{data.interview && <button onClick={() => navigate(`/manager/interviews/${data.interview.interviewId}`)}>View Interview</button>}</div></header>{error && <div className={styles.error}>{error}</div>}<div className={styles.detailGrid}><main><section><h2>Candidate Profile</h2><div className={styles.fields}><p><b>Email</b>{data.candidate.email}</p><p><b>Phone</b>{data.candidate.phone || 'Not provided'}</p></div><h3>Professional Summary</h3><p>{data.candidate.professionalSummary || 'Not provided'}</p><h3>Education</h3><p>{data.candidate.education || 'Not provided'}</p><h3>Experience</h3><p>{data.candidate.experience || 'Not provided'}</p><h3>Skills</h3><div className={styles.skills}>{data.candidate.skills.length ? data.candidate.skills.map(x => <span key={x}>{x}</span>) : 'Not provided'}</div><div className={styles.links}>{data.candidate.linkedInUrl && <a href={data.candidate.linkedInUrl} target="_blank" rel="noreferrer">LinkedIn</a>}{data.candidate.portfolioUrl && <a href={data.candidate.portfolioUrl} target="_blank" rel="noreferrer">Portfolio</a>}</div></section><section><h2>Cover Letter</h2><p>{data.coverLetter || 'No cover letter was submitted.'}</p></section></main><aside><section><h2>Job Summary</h2><h3>{data.job.title}</h3><p>{data.job.departmentName || 'No department'}</p><p>{data.job.location} · {data.job.employmentType}</p><p>{data.job.requirements || 'Requirements not provided.'}</p></section><section><h2>Application</h2><p>Applied {new Date(data.appliedOn).toLocaleString()}</p>{data.resume ? <button onClick={download}>Download {data.resume.displayName}</button> : <p>No resume attached</p>}</section>{data.interview && <section><h2>Interview</h2><p>{new Date(data.interview.scheduledAt).toLocaleString()}</p><p>{data.interview.status} · {data.interview.durationMinutes} minutes</p></section>}{data.existingEvaluation && <section><h2>Existing Evaluation</h2><p>Score: {data.existingEvaluation.overallScore}</p><p>{data.existingEvaluation.hiringDecision}</p></section>}</aside></div></>}</DashboardLayout>
}
