import {useCallback,useEffect,useState} from 'react'
import {useNavigate} from 'react-router-dom'
import DashboardLayout from '../components/dashboard/DashboardLayout'
import RecruiterSidebar from '../components/recruiter/RecruiterSidebar'
import RecruiterNavbar from '../components/recruiter/RecruiterNavbar'
import {useAuth} from '../context/AuthContext'
import {closeRecruiterJob,deleteRecruiterJob,getRecruiterJobs,publishRecruiterJob} from '../services/recruiterJobService'
import styles from './RecruiterJobs.module.css'

export default function RecruiterJobs(){
 const [menu,setMenu]=useState(false),[result,setResult]=useState({items:[],page:1,totalPages:0,totalItems:0}),[query,setQuery]=useState({search:'',status:'',page:1,pageSize:10,sort:'newest'}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(null);const {logout,user}=useAuth(),navigate=useNavigate()
 const load=useCallback(()=>{const controller=new AbortController();setLoading(true);setError('');getRecruiterJobs(query,controller.signal).then(setResult).catch(e=>{if(e.name!=='CanceledError')setError('Could not load your jobs.')}).finally(()=>setLoading(false));return()=>controller.abort()},[query])
 useEffect(()=>load(),[load])
 const mutate=async(job,action)=>{if(action==='delete'&&!window.confirm(`Delete ${job.title}?`))return;setBusy(job.jobId);setError('');try{if(action==='publish')await publishRecruiterJob(job.jobId);if(action==='close')await closeRecruiterJob(job.jobId);if(action==='delete')await deleteRecruiterJob(job.jobId);load()}catch(e){setError(e.response?.data?.title||'The job could not be updated.')}finally{setBusy(null)}}
 const set=(key,value)=>setQuery(x=>({...x,[key]:value,page:1}));const signOut=()=>{logout();navigate('/login',{replace:true})}
 return <DashboardLayout sidebar={<RecruiterSidebar isOpen={menu} onClose={()=>setMenu(false)} onLogout={signOut}/>} navbar={<RecruiterNavbar user={user} onMenuClick={()=>setMenu(true)}/>}><div className={styles.heading}><div><h1>Manage Jobs</h1><p>Review and manage opportunities posted by your organization.</p></div><button onClick={()=>navigate('/recruiter/jobs/new')}>+ Post a Job</button></div><div className={styles.filters}><input aria-label="Search jobs" placeholder="Search jobs" value={query.search} onChange={e=>set('search',e.target.value)}/><select aria-label="Filter by status" value={query.status} onChange={e=>set('status',e.target.value)}><option value="">All statuses</option><option>Draft</option><option>Published</option><option>Closed</option><option>Paused</option><option>Archived</option></select><select aria-label="Sort jobs" value={query.sort} onChange={e=>set('sort',e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="closing">Closing soon</option></select></div>{error&&<div className={styles.error}>{error}<button onClick={load}>Retry</button></div>}{loading?<div className={styles.skeleton}>Loading jobs…</div>:result.items.length===0?<div className={styles.empty}><h2>No jobs found</h2><p>Try changing the filters or post a new opportunity.</p></div>:<div className={styles.jobs}>{result.items.map(job=><article key={job.jobId}><div className={styles.jobMain}><div><span className={`${styles.badge} ${styles[job.status.toLowerCase()]}`}>{job.status}</span><h2>{job.title}</h2><p>{job.departmentName} · {job.location} · {job.employmentType}</p></div><strong>{job.applicationCount} applicant{job.applicationCount===1?'':'s'}</strong></div><div className={styles.meta}><span>Created {new Date(job.createdAt).toLocaleDateString()}</span><span>{job.closingDate?`Closes ${new Date(job.closingDate).toLocaleDateString()}`:'No closing date'}</span></div><div className={styles.actions}><button onClick={()=>navigate(`/recruiter/jobs/${job.jobId}`)}>View</button><button onClick={()=>navigate(`/recruiter/jobs/${job.jobId}/edit`)}>Edit</button><button onClick={()=>navigate(`/recruiter/jobs/${job.jobId}/applications`)}>Applicants</button>{job.status==='Draft'&&<button disabled={busy===job.jobId} onClick={()=>mutate(job,'publish')}>Publish</button>}{job.status==='Published'&&<button disabled={busy===job.jobId} onClick={()=>mutate(job,'close')}>Close</button>}<button className={styles.delete} disabled={busy===job.jobId} onClick={()=>mutate(job,'delete')}>Delete</button></div></article>)}</div>}<div className={styles.pagination}><button disabled={result.page<=1} onClick={()=>setQuery(x=>({...x,page:x.page-1}))}>Previous</button><span>Page {result.page} of {Math.max(result.totalPages,1)}</span><button disabled={result.page>=result.totalPages} onClick={()=>setQuery(x=>({...x,page:x.page+1}))}>Next</button></div></DashboardLayout>
}
