import { useCallback,useEffect,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import DashboardLayout from '../components/dashboard/DashboardLayout'
import RecruiterSidebar from '../components/recruiter/RecruiterSidebar'
import RecruiterNavbar from '../components/recruiter/RecruiterNavbar'
import UpcomingInterviewsPanel from '../components/recruiter/UpcomingInterviewsPanel'
import ApplicationsOverviewChart from '../components/recruiter/ApplicationsOverviewChart'
import { useAuth } from '../context/AuthContext'
import { emptyRecruiterStats,getRecruiterDashboardStats,getRecruiterRecentApplicants,getRecruiterUpcomingInterviews,getRecruiterApplicationsOverview } from '../services/recruiterDashboardService'
import styles from './RecruiterDashboard.module.css'
const cards=[['totalJobs','Total Jobs','Active job posts'],['totalApplications','Total Applications','All time applications'],['totalCandidates','Total Candidates','Unique candidates'],['interviewsThisMonth','Interviews','This month']]
const statusTone={Submitted:'pending',UnderReview:'pending',Shortlisted:'shortlisted',Interviewing:'interview',Rejected:'rejected',Offered:'shortlisted',Hired:'shortlisted'}
const date=value=>new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value))
export default function RecruiterDashboard(){
 const [open,setOpen]=useState(false),[stats,setStats]=useState(emptyRecruiterStats),[loading,setLoading]=useState(true),[error,setError]=useState(false),[applicants,setApplicants]=useState([]),[applicantsLoading,setApplicantsLoading]=useState(true),[applicantsError,setApplicantsError]=useState(false),[interviews,setInterviews]=useState([]),[interviewsLoading,setInterviewsLoading]=useState(true),[interviewsError,setInterviewsError]=useState(false),[overview,setOverview]=useState([]),[overviewLoading,setOverviewLoading]=useState(true),[overviewError,setOverviewError]=useState(false);const {logout,user}=useAuth(),navigate=useNavigate()
 const load=useCallback(async signal=>{setLoading(true);setError(false);try{setStats(await getRecruiterDashboardStats(signal))}catch(e){if(e.name!=='CanceledError'){setStats(emptyRecruiterStats);setError(true)}}finally{if(!signal?.aborted)setLoading(false)}},[])
 const loadApplicants=useCallback(async signal=>{setApplicantsLoading(true);setApplicantsError(false);try{setApplicants(await getRecruiterRecentApplicants(signal))}catch(e){if(e.name!=='CanceledError'){setApplicants([]);setApplicantsError(true)}}finally{if(!signal?.aborted)setApplicantsLoading(false)}},[])
 const loadInterviews=useCallback(async signal=>{setInterviewsLoading(true);setInterviewsError(false);try{setInterviews(await getRecruiterUpcomingInterviews(signal))}catch(e){if(e.name!=='CanceledError'){setInterviews([]);setInterviewsError(true)}}finally{if(!signal?.aborted)setInterviewsLoading(false)}},[])
 const loadOverview=useCallback(async signal=>{setOverviewLoading(true);setOverviewError(false);try{setOverview(await getRecruiterApplicationsOverview(signal))}catch(e){if(e.name!=='CanceledError'){setOverview([]);setOverviewError(true)}}finally{if(!signal?.aborted)setOverviewLoading(false)}},[])
 useEffect(()=>{const c=new AbortController();load(c.signal);return()=>c.abort()},[load]);useEffect(()=>{const c=new AbortController();loadApplicants(c.signal);return()=>c.abort()},[loadApplicants]);useEffect(()=>{const c=new AbortController();loadInterviews(c.signal);return()=>c.abort()},[loadInterviews]);useEffect(()=>{const c=new AbortController();loadOverview(c.signal);return()=>c.abort()},[loadOverview]);const signOut=()=>{logout();navigate('/login',{replace:true})}
 return <DashboardLayout sidebar={<RecruiterSidebar isOpen={open} onClose={()=>setOpen(false)} onLogout={signOut}/>} navbar={<RecruiterNavbar user={user} onMenuClick={()=>setOpen(true)}/>}><header className={styles.heading}><h1>Recruiter Dashboard</h1><p>Manage your jobs, candidates and hiring pipeline.</p></header><section className={styles.stats}>{cards.map(([key,label,caption])=><article key={key}><span>{label}</span>{loading?<i/>:<strong>{stats[key]}</strong>}<small>{caption}</small></article>)}</section>{error&&<div className={styles.error}>Could not load dashboard statistics.<button onClick={()=>load()}>Retry</button></div>}<section className={styles.recent}><header><h2>Recent Applicants</h2><button>View All</button></header><div className={styles.tableWrap}><table><thead><tr><th>Candidate</th><th>Job</th><th>Applied On</th><th>Status</th></tr></thead><tbody>{applicantsLoading&&[1,2,3].map(row=><tr key={row} className={styles.loadingRow}><td colSpan="4"><i/></td></tr>)}{!applicantsLoading&&applicants.map(a=><tr key={a.applicationId}><td>{a.profileImageUrl?<img className={styles.avatar} src={a.profileImageUrl} alt=""/>:<b className={styles.avatar}>{a.candidateName?.[0]?.toUpperCase()||'C'}</b>}{a.candidateName}</td><td>{a.jobTitle}</td><td>{date(a.appliedOn)}</td><td><em className={styles[statusTone[a.status]||'pending']}>{a.status}</em></td></tr>)}{!applicantsLoading&&!applicantsError&&!applicants.length&&<tr><td colSpan="4" className={styles.empty}>No recent applicants</td></tr>}{!applicantsLoading&&applicantsError&&<tr><td colSpan="4" className={styles.empty}>Could not load applicants. <button onClick={()=>loadApplicants()}>Retry</button></td></tr>}</tbody></table></div></section><div className={styles.lower}><UpcomingInterviewsPanel items={interviews} isLoading={interviewsLoading} hasError={interviewsError} onRetry={()=>loadInterviews()}/><ApplicationsOverviewChart months={overview} isLoading={overviewLoading} hasError={overviewError} onRetry={()=>loadOverview()}/></div></DashboardLayout>
}
