import {useEffect,useState} from 'react'
import {useNavigate,useParams} from 'react-router-dom'
import DashboardLayout from '../components/dashboard/DashboardLayout'
import RecruiterSidebar from '../components/recruiter/RecruiterSidebar'
import RecruiterNavbar from '../components/recruiter/RecruiterNavbar'
import {useAuth} from '../context/AuthContext'
import {createRecruiterJob,getRecruiterDepartments,getRecruiterJob,getRecruiterSkills,updateRecruiterJob} from '../services/recruiterJobService'
import {getPublicPlatformSettings} from '../services/adminSystemSettingsService'
import styles from './RecruiterPostJob.module.css'
const initial={title:'',departmentId:'',location:'',employmentType:'Full-time',description:'',responsibilities:'',requirements:'',minimumSalary:'',maximumSalary:'',closingDate:'',skillIds:[]}
const localDate=value=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):''
export default function RecruiterPostJob({editMode=false}){
 const [open,setOpen]=useState(false),[form,setForm]=useState(initial),[departments,setDepartments]=useState([]),[skills,setSkills]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const {jobId}=useParams(),{logout,user}=useAuth(),navigate=useNavigate()
 useEffect(()=>{const c=new AbortController();const requests=[getRecruiterDepartments(c.signal),getRecruiterSkills(c.signal),getPublicPlatformSettings(c.signal)];if(editMode)requests.push(getRecruiterJob(jobId,c.signal));Promise.all(requests).then(([d,s,platform,job])=>{setDepartments(d);setSkills(s);if(job)setForm({title:job.title,departmentId:String(job.departmentId),location:job.location,employmentType:job.employmentType,description:job.description,responsibilities:job.responsibilities||'',requirements:job.requirements||'',minimumSalary:job.minimumSalary??'',maximumSalary:job.maximumSalary??'',closingDate:localDate(job.closingDate),skillIds:job.skills.map(x=>x.id)});else setForm(x=>({...x,closingDate:localDate(new Date(Date.now()+platform.defaultJobClosingDays*86400000))}))}).catch(e=>{if(e.name!=='CanceledError')setMessage('Could not load the job form.')}).finally(()=>setLoading(false));return()=>c.abort()},[editMode,jobId])
 const change=e=>setForm(x=>({...x,[e.target.name]:e.target.value})),toggle=id=>setForm(x=>({...x,skillIds:x.skillIds.includes(id)?x.skillIds.filter(y=>y!==id):[...x.skillIds,id]}));const payload=()=>({...form,departmentId:Number(form.departmentId),minimumSalary:form.minimumSalary===''?null:Number(form.minimumSalary),maximumSalary:form.maximumSalary===''?null:Number(form.maximumSalary),closingDate:new Date(form.closingDate).toISOString()})
 async function submit(publishNow=false){if(busy)return;setBusy(true);setMessage('');try{if(editMode){await updateRecruiterJob(jobId,payload());navigate(`/recruiter/jobs/${jobId}`)}else{const result=await createRecruiterJob({...payload(),publishNow});navigate(`/recruiter/jobs/${result.jobId}`)}}catch(e){setMessage(e.response?.data?.detail||e.response?.data?.title||Object.values(e.response?.data?.errors||{})[0]?.[0]||'Could not save the job.')}finally{setBusy(false)}}
 const signOut=()=>{logout();navigate('/login',{replace:true})};return <DashboardLayout sidebar={<RecruiterSidebar isOpen={open} onClose={()=>setOpen(false)} onLogout={signOut}/>} navbar={<RecruiterNavbar user={user} onMenuClick={()=>setOpen(true)}/>}><header className={styles.header}><h1>{editMode?'Edit Job':'Post a Job'}</h1><p>{editMode?'Update the opportunity details.':'Create a new opportunity for your organization.'}</p></header>{loading?<div className={styles.skeleton}/>:<form className={styles.form} onSubmit={e=>{e.preventDefault();submit()}}><section><h2>Basic Information</h2><div className={styles.grid}><label>Job title<input required maxLength="200" name="title" value={form.title} onChange={change}/></label><label>Department<select required name="departmentId" value={form.departmentId} onChange={change}><option value="">Select department</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Location<input required maxLength="200" name="location" value={form.location} onChange={change}/></label><label>Employment type<select name="employmentType" value={form.employmentType} onChange={change}><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Internship</option><option>Remote</option></select></label></div></section><section><h2>Job Description</h2><label>Description<textarea required maxLength="8000" name="description" value={form.description} onChange={change}/></label><label>Responsibilities<textarea maxLength="8000" name="responsibilities" value={form.responsibilities} onChange={change}/></label><label>Requirements<textarea maxLength="8000" name="requirements" value={form.requirements} onChange={change}/></label></section><section><h2>Compensation and Deadline</h2><div className={styles.grid}><label>Minimum salary<input min="0" type="number" name="minimumSalary" value={form.minimumSalary} onChange={change}/></label><label>Maximum salary<input min="0" type="number" name="maximumSalary" value={form.maximumSalary} onChange={change}/></label><label>Closing date<input required type="datetime-local" name="closingDate" value={form.closingDate} onChange={change}/></label></div></section><section><h2>Skills</h2><p>Select the skills required for this role.</p><div className={styles.chips}>{skills.map(x=><button className={form.skillIds.includes(x.id)?styles.selected:''} type="button" key={x.id} onClick={()=>toggle(x.id)}>{x.name}</button>)}</div></section>{message&&<div className={styles.message}>{message}</div>}<div className={styles.actions}><button type="button" onClick={()=>navigate(editMode?`/recruiter/jobs/${jobId}`:'/recruiter/jobs')}>Cancel</button><button disabled={busy} type="submit">{busy?'Saving…':editMode?'Save Changes':'Save as Draft'}</button>{!editMode&&<button disabled={busy} type="button" className={styles.publish} onClick={()=>submit(true)}>Publish Job</button>}</div></form>}</DashboardLayout>
}
