import { useCallback, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import DashboardLayout from '../components/dashboard/DashboardLayout'
import RecruiterSidebar from '../components/recruiter/RecruiterSidebar'
import RecruiterNavbar from '../components/recruiter/RecruiterNavbar'
import { useAuth } from '../context/AuthContext'
import { changeRecruiterPassword, getRecruiterSettings, updateRecruiterSettings } from '../services/recruiterSettingsService'
import styles from './RecruiterSettings.module.css'

const preferences = [
  ['jobApplicationNotifications', 'New job applications', 'Receive updates when candidates apply to your jobs.'],
  ['interviewNotifications', 'Interview notifications', 'Receive reminders and interview updates.'],
  ['candidateStatusNotifications', 'Candidate status updates', 'Track changes throughout the recruitment pipeline.'],
  ['emailNotifications', 'Email notifications', 'Receive selected notifications by email.'],
]

export default function RecruiterSettings() {
  const [open, setOpen] = useState(false), [settings, setSettings] = useState(null), [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [message, setMessage] = useState(''), [error, setError] = useState('')
  const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirmNewPassword: '' }), [show, setShow] = useState(false)
  const { user, logout, refreshUser } = useAuth(), navigate = useNavigate()
  const load = useCallback(signal => { setLoading(true); setError(''); getRecruiterSettings(signal).then(setSettings).catch(e => { if (e.name !== 'CanceledError') setError('Could not load recruiter settings.') }).finally(() => setLoading(false)) }, [])
  useEffect(() => { const controller = new AbortController(); load(controller.signal); return () => controller.abort() }, [load])
  const change = e => setSettings(x => ({ ...x, [e.target.name]: e.target.value }))
  async function save(section) { if (busy) return; setBusy(section); setMessage(''); setError(''); try { setSettings(await updateRecruiterSettings(settings)); if (section === 'profile') await refreshUser(); setMessage(section === 'profile' ? 'Profile saved successfully.' : 'Preferences saved successfully.') } catch (e) { setError(e.response?.data?.detail || Object.values(e.response?.data?.errors || {})[0]?.[0] || 'Unable to save settings.') } finally { setBusy('') } }
  async function changePassword(e) { e.preventDefault(); if (busy) return; if (passwords.newPassword !== passwords.confirmNewPassword) { setError('New password and confirmation must match.'); return } setBusy('password'); setMessage(''); setError(''); try { await changeRecruiterPassword(passwords); setPasswords({ currentPassword: '', newPassword: '', confirmNewPassword: '' }); setMessage('Password changed successfully.') } catch (e) { setError(e.response?.data?.title || Object.values(e.response?.data?.errors || {})[0]?.[0] || 'Unable to change password.') } finally { setBusy('') } }
  return <DashboardLayout sidebar={<RecruiterSidebar isOpen={open} onClose={() => setOpen(false)} onLogout={() => { logout(); navigate('/login') }} />} navbar={<RecruiterNavbar user={user} onMenuClick={() => setOpen(true)} />}><header className={styles.header}><h1>Settings</h1><p>Manage your recruiter profile, notifications, and security.</p></header>{loading ? <div className={styles.skeleton}>Loading settings…</div> : error && !settings ? <div className={styles.errorState}>{error}<button onClick={() => load()}>Retry</button></div> : settings && <div className={styles.sections}><section className={styles.card}><h2>Profile Settings</h2><p>Your email address is read-only.</p><div className={styles.profileGrid}><label>First name<input required maxLength="100" name="firstName" value={settings.firstName} onChange={change} /></label><label>Last name<input required maxLength="100" name="lastName" value={settings.lastName} onChange={change} /></label><label>Email<input disabled value={settings.email} /></label><label>Phone<input maxLength="30" name="phone" value={settings.phone || ''} onChange={change} /></label></div><button disabled={Boolean(busy) || !settings.firstName.trim() || !settings.lastName.trim()} onClick={() => save('profile')}>{busy === 'profile' ? 'Saving…' : 'Save Profile'}</button></section><section className={styles.card}><h2>Notification Preferences</h2><p>Choose which recruiter updates you want to receive.</p><div className={styles.preferences}>{preferences.map(([key, label, description]) => <label key={key}><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={settings[key]} onChange={e => setSettings(x => ({ ...x, [key]: e.target.checked }))} /><i /></label>)}</div><button disabled={Boolean(busy)} onClick={() => save('preferences')}>{busy === 'preferences' ? 'Saving…' : 'Save Preferences'}</button></section><form className={styles.card} onSubmit={changePassword}><h2>Security</h2><p>Use at least 10 characters with uppercase, lowercase, and a number.</p><div className={styles.passwordGrid}>{[['currentPassword', 'Current password'], ['newPassword', 'New password'], ['confirmNewPassword', 'Confirm new password']].map(([key, label]) => <label key={key}>{label}<input required minLength={key === 'currentPassword' ? 1 : 10} maxLength="128" type={show ? 'text' : 'password'} value={passwords[key]} onChange={e => setPasswords(x => ({ ...x, [key]: e.target.value }))} /></label>)}</div><label className={styles.show}><input type="checkbox" checked={show} onChange={e => setShow(e.target.checked)} /> Show passwords</label><button disabled={Boolean(busy)}>{busy === 'password' ? 'Changing…' : 'Change Password'}</button></form>{message && <div className={styles.success}>{message}</div>}{error && <div className={styles.error}>{error}</div>}</div>}</DashboardLayout>
}
