using System.ComponentModel.DataAnnotations;using JobOrbit.Application.DTOs.Jobs;
namespace JobOrbit.Application.DTOs.AdminUsers;
public sealed class AdminUserQuery{public string?Search{get;set;}public string?Role{get;set;}public string?Status{get;set;}public int?OrganizationId{get;set;}public int?DepartmentId{get;set;}public int Page{get;set;}=1;public int PageSize{get;set;}=10;public string Sort{get;set;}="newest";}
public sealed class AdminUserListItemDto{public int UserId{get;init;}public string FullName{get;init;}="";public string Email{get;init;}="";public string Role{get;init;}="";public string Status{get;init;}="";public string?OrganizationName{get;init;}public string?DepartmentName{get;init;}public DateTime CreatedAt{get;init;}public DateTime?LastLoginAt{get;init;}}
public sealed class AdminUserDetailsDto{public int UserId{get;init;}public string FirstName{get;init;}="";public string LastName{get;init;}="";public string FullName{get;init;}="";public string Email{get;init;}="";public string?Phone{get;init;}public string Role{get;init;}="";public string Status{get;init;}="";public int?OrganizationId{get;init;}public string?OrganizationName{get;init;}public int?DepartmentId{get;init;}public string?DepartmentName{get;init;}public DateTime CreatedAt{get;init;}public DateTime UpdatedAt{get;init;}public DateTime?LastLoginAt{get;init;}public string?ProfessionalTitle{get;init;}public string?Education{get;init;}public IReadOnlyList<string>Skills{get;init;}=[];public string?JobTitle{get;init;}}
public sealed class CreateAdminUserRequest{[Required,StringLength(100,MinimumLength=1)]public string FirstName{get;init;}="";[Required,StringLength(100,MinimumLength=1)]public string LastName{get;init;}="";[Required,EmailAddress,StringLength(320)]public string Email{get;init;}="";[StringLength(30),RegularExpression(@"^[0-9+()\-\s]*$")]public string?Phone{get;init;}[Required]public string Role{get;init;}="";public int?OrganizationId{get;init;}public int?DepartmentId{get;init;}[Required,StringLength(128,MinimumLength=10),RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$")]public string TemporaryPassword{get;init;}="";public bool IsActive{get;init;}=true;}
public sealed class UpdateAdminUserRequest{[Required,StringLength(100,MinimumLength=1)]public string FirstName{get;init;}="";[Required,StringLength(100,MinimumLength=1)]public string LastName{get;init;}="";[StringLength(30),RegularExpression(@"^[0-9+()\-\s]*$")]public string?Phone{get;init;}[Required]public string Role{get;init;}="";public int?OrganizationId{get;init;}public int?DepartmentId{get;init;}}
public sealed class UpdateUserStatusRequest{public bool IsActive{get;init;}[StringLength(1000)]public string?Reason{get;init;}}
public sealed class AdminResetPasswordRequest{[Required,StringLength(128,MinimumLength=10),RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$")]public string TemporaryPassword{get;init;}="";[Required,Compare(nameof(TemporaryPassword))]public string ConfirmTemporaryPassword{get;init;}="";public bool RequirePasswordChange{get;init;}=true;}
public enum AdminUserMutationOutcome{Success,NotFound,DuplicateEmail,InvalidRole,InvalidOrganization,InvalidDepartment,DangerousRoleChange,SelfStatusChange,LastActiveAdmin}
public sealed record AdminUserMutationResult(AdminUserMutationOutcome Outcome,AdminUserDetailsDto?User=null);
