using System.Security.Claims;using JobOrbit.API.Controllers;using JobOrbit.Application.DTOs.HiringManagerInterviews;using JobOrbit.Application.DTOs.Jobs;using JobOrbit.Application.Interfaces;using JobOrbit.Application.Services;using JobOrbit.Domain.Enums;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Http;using Microsoft.AspNetCore.Mvc;
namespace JobOrbit.Tests;
public sealed class HiringManagerInterviewServiceTests
{
 [Fact]public async Task ListAsync_NormalizesPagingAndUsesAuthenticatedManager(){var repo=new FakeRepository();var service=new HiringManagerInterviewService(repo);var query=new HiringManagerInterviewQuery{Page=0,PageSize=500};await service.ListAsync(12,query);Assert.Equal(12,repo.UserId);Assert.Equal(1,query.Page);Assert.Equal(50,query.PageSize);}
 [Fact]public async Task Controller_ReadsUserIdClaimForList(){var service=new FakeService();var controller=new HiringManagerInterviewsController(service){ControllerContext=new(){HttpContext=new DefaultHttpContext{User=new ClaimsPrincipal(new ClaimsIdentity([new Claim("UserId","14")],"test"))}}};var result=await controller.List(new HiringManagerInterviewQuery(),CancellationToken.None);Assert.IsType<OkObjectResult>(result.Result);Assert.Equal(14,service.UserId);}
 [Fact]public void Controller_IsHiringManagerOnly(){var attribute=Assert.Single(typeof(HiringManagerInterviewsController).GetCustomAttributes(typeof(AuthorizeAttribute),true).Cast<AuthorizeAttribute>());Assert.Equal(nameof(UserRole.HiringManager),attribute.Roles);}
 [Fact]public async Task Controller_RejectsInvalidDateRange(){var controller=new HiringManagerInterviewsController(new FakeService()){ControllerContext=new(){HttpContext=new DefaultHttpContext{User=new ClaimsPrincipal(new ClaimsIdentity([new Claim("UserId","14")],"test"))}}};var result=await controller.List(new(){From=DateTime.UtcNow,To=DateTime.UtcNow.AddDays(-1)},CancellationToken.None);Assert.IsType<BadRequestObjectResult>(result.Result);}
 private sealed class FakeRepository:IHiringManagerInterviewRepository{public int UserId{get;private set;}public Task<HiringManagerInterviewDetailsDto?>DetailsAsync(int u,int i,CancellationToken t=default)=>Task.FromResult<HiringManagerInterviewDetailsDto?>(null);public Task<PagedResultDto<HiringManagerInterviewListItemDto>>ListAsync(int u,HiringManagerInterviewQuery q,CancellationToken t=default){UserId=u;return Task.FromResult(new PagedResultDto<HiringManagerInterviewListItemDto>());}}
 private sealed class FakeService:IHiringManagerInterviewService{public int UserId{get;private set;}public Task<HiringManagerInterviewDetailsDto?>DetailsAsync(int u,int i,CancellationToken t=default)=>Task.FromResult<HiringManagerInterviewDetailsDto?>(null);public Task<PagedResultDto<HiringManagerInterviewListItemDto>>ListAsync(int u,HiringManagerInterviewQuery q,CancellationToken t=default){UserId=u;return Task.FromResult(new PagedResultDto<HiringManagerInterviewListItemDto>());}}
}
